spring.datasource.url=jdbc:postgresql://localhost:5432/youtube_clone

spring.datasource.username=postgres

spring.datasource.password=mypostgres

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=mysecret123423@#sghsfg3456754
jwt.access-token-expiration=900000