spring.datasource.url=jdbc:postgresql://localhost:5432/youtube_clone

spring.datasource.username=postgres

spring.datasource.password=mypostgres

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=my-super-secret-key-for-jwt-authentication-123
jwt.access-token-expiration=900000
jwt.refresh-token-expiration =7